services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./playground-realm.json:/opt/keycloak/data/import/playground-realm.json
      - ./target/recaptcha-login.jar:/opt/keycloak/providers/recaptcha-login.jar
    ports:
      - 8080:8080
